[TRAINING]
healthy_skin_path = './dataset/healthy/'
diseased_skin_path = './dataset/diseased/'
training_dataset_ratio = 0.8
precision_threshold = 0.9
num_epochs = 10
num_workers = 4
batch_size = 32
shuffle = true
pin_memory = true