[TRAINING]
healthy_skin_path = './dataset/healthy/'
diseased_skin_path = './dataset/diseased/'
training_dataset_ratio = 0.8
precision_threshold = 0.9
batch_size = 32
num_workers = 4
shuffle = true
pin_memory = true