[TRAINING]
num_epochs = 3
num_workers = 12
batch_size = 128
learning_rate = 0.0001
shuffle = true
pin_memory = true
resize_dim = 128

[PREPROCESS]
normalize.mean = 0.4
normalize.std = 0.2
denoise.kernel_size = 5
denoise.sigma_space = 19
denoise.sigma_color = 10
colorspace.source_space = 'RGB'
colorspace.target_space = 'HSV'
