[TRAINING]
healthy_skin_path = './dataset/healthy/'
diseased_skin_path = './dataset/diseased/'
training_dataset_ratio = 0.8
precision_threshold = 0.9
num_epochs = 15
num_workers = 10
batch_size = 64
learning_rate = 0.000075
shuffle = true
pin_memory = true